### ISSUE TITLE
feature request: suppot status LEDs

### ISSUE THREAD

**Issue by nerdralph** [pyocd/pyOCD#1053] opened 2021-01-16 18:20 UTC
The DAP_HostStatus can be used to control 2 debug probe LEDs: connected and running.  pyocd currently does not use or define this message.

**Comment by flit** [comment] 2021-01-17 22:00
Closing as duplicate of #982.

**Closed by flit** 2021-01-17 22:00 UTC
Labels: duplicate

**Comment by flit** [comment] 2021-01-17 22:02
Your vote for this feature has been counted. 😀
