### ISSUE TITLE
Eclipse and pyOCD v0.28.2, pyOCD can not start debugging.

### ISSUE THREAD

**Issue by lennvn** [pyocd/pyOCD#990] opened 2020-11-03 01:47 UTC
I updated pyCOD to v0.28.2. When I launch the pyOCD debug configuration, pyCOD stop at "0001590:INFO:server:Semihost server started on port 4444 (core 0)" and the there's no debug window. I used pyOCD 0.22.1 before.

**Comment by danielRep** [comment] 2020-11-03 10:16
Afaik, in the case that you're using "Embedded C/C++ PyOCD Debugging" plugin as me, I experience the same issue as you. The problem is related with the use of the deprecated pyocd-gdbserver which is typically setup. I was able to get things working by starting the "pyocd gdb" server externally in a terminal. 

PS: I didn't test it, but yesterday @flit commit could be possibly solving that issue (https://github.com/pyocd/pyOCD/commit/1ba9b17f3288aaeecb168116b1ff556c678bc105). Hope that works for you.

**Comment by flit** [comment] 2020-11-03 17:24
Yes, #988 fixes the problem with starting `pyocd-gdbserver`. (The problem was reported by @joergw on the Eclipse Embedded CDT forum.)

I'm going to go ahead and close this issue since the fix is committed. A 0.28.3 version will be released probably today or tomorrow that includes the fix.

**Closed by flit** 2020-11-03 17:24 UTC
Labels: bug

**Comment by danielRep** [comment] 2020-11-04 20:44
That kind of improvements will be great @flit !
