### ISSUE TITLE
dap protocol jtag is an error when used

### ISSUE THREAD

**Issue by LONGZR007** [pyocd/pyOCD#992] opened 2020-11-04 08:57 UTC

**Comment by flit** [comment] 2020-11-04 20:06
That's right, JTAG is not fully supported yet. (Because there is not much reason to support it, as almost every Cortex-M target support SWD, which is more efficient.) It's on the list to be implemented soon, however.

**Comment by flit** [comment] 2020-11-04 20:07
Closing this issue: duplicate of #593.

**Closed by flit** 2020-11-04 20:07 UTC
Labels: duplicate
